# This file was generated by GoReleaser. DO NOT EDIT.
cask "safecut" do
  version "2.0.2"

  on_macos do
    on_intel do
      sha256 "9bb243cc9508545d71bf2becbd9fbb444897fc0331112ba1d5d034746620ee74"
      url "https://github.com/Rafaelhdsg/safecut/releases/download/v#{version}/safecut_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "45a1f271cc3c0bd8f52742798e8b7516d902ae1b0b20a0cec3421862218509bd"
      url "https://github.com/Rafaelhdsg/safecut/releases/download/v#{version}/safecut_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b76c7b53cda27eaea6e65766cb5aa3950238ea3f5da85ebf30aa99fa2e67151c"
      url "https://github.com/Rafaelhdsg/safecut/releases/download/v#{version}/safecut_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "317bfa9ebeb04d90c18218e7b79a2a7e6ad0538920c58674433fec37db0c14a0"
      url "https://github.com/Rafaelhdsg/safecut/releases/download/v#{version}/safecut_#{version}_linux_arm64.tar.gz"
    end
  end

  name "safecut"
  desc "The cuts you'd defend at standup — find idle resources, simulate safely, and stop paying for what you don't use"
  homepage "https://github.com/Rafaelhdsg/safecut"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "safecut"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/safecut"]
    end
  end

  # No zap stanza required

end
