# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Inframind < Formula
  desc "Decision engine for cloud infrastructure — analyze, simulate, and optimize costs"
  homepage "https://github.com/Rafaelhdsg/inframind-cli"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Rafaelhdsg/inframind-cli/releases/download/v1.0.0/inframind_1.0.0_darwin_amd64.tar.gz"
      sha256 "b2467354dd81048c6ec812cacf4cb2302037b9c4ec1b19d8493b9441ed1b099f"

      define_method(:install) do
        bin.install "inframind"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Rafaelhdsg/inframind-cli/releases/download/v1.0.0/inframind_1.0.0_darwin_arm64.tar.gz"
      sha256 "1a3d8a7d956446b3faae29632e356ea1a8a48b1cb307676d6bce54d1c1b5249f"

      define_method(:install) do
        bin.install "inframind"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Rafaelhdsg/inframind-cli/releases/download/v1.0.0/inframind_1.0.0_linux_amd64.tar.gz"
      sha256 "d7c544109381362b87e70941e39eeee0847dc095276a1ee9d334cce62b1f8b68"
      define_method(:install) do
        bin.install "inframind"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Rafaelhdsg/inframind-cli/releases/download/v1.0.0/inframind_1.0.0_linux_arm64.tar.gz"
      sha256 "3c10ce6385c2a01d548da2000a6d4da95f29d9b5842024bff5ef1b7be989f258"
      define_method(:install) do
        bin.install "inframind"
      end
    end
  end

  test do
    # Both forms must work: the explicit subcommand (stable API for
    # scripts/CI) and the cobra --version flag.
    assert_match "inframind", shell_output("#{bin}/inframind version")
    system "#{bin}/inframind", "--version"
    system "#{bin}/inframind", "--help"
  end
end
