# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Safecut < Formula
  desc "The cuts you'd defend at standup — find idle resources, simulate safely, and stop paying for what you don't use"
  homepage "https://github.com/Rafaelhdsg/safecut"
  version "2.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Rafaelhdsg/safecut/releases/download/v2.0.0/safecut_2.0.0_darwin_amd64.tar.gz"
      sha256 "ec227af49d3e02c18f87d5fc7e5bb8f715647f78849c90f593ec78c11f71ddf7"

      define_method(:install) do
        bin.install "safecut"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Rafaelhdsg/safecut/releases/download/v2.0.0/safecut_2.0.0_darwin_arm64.tar.gz"
      sha256 "b374a70705d5984aa24c23e1805029b938c92c90b8b9b9d0866d94838e01da2e"

      define_method(:install) do
        bin.install "safecut"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Rafaelhdsg/safecut/releases/download/v2.0.0/safecut_2.0.0_linux_amd64.tar.gz"
      sha256 "60353941887d3e509881150bbd65a025b9fdf75571583f5b97407ce03fdcf0db"
      define_method(:install) do
        bin.install "safecut"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Rafaelhdsg/safecut/releases/download/v2.0.0/safecut_2.0.0_linux_arm64.tar.gz"
      sha256 "03788563f451be9289d50a94253e6130a544fb8eef9cf63bed23730183e285f3"
      define_method(:install) do
        bin.install "safecut"
      end
    end
  end

  test do
    # Both forms must work: the explicit subcommand (stable API for
    # scripts/CI) and the cobra --version flag.
    assert_match "safecut", shell_output("#{bin}/safecut version")
    system "#{bin}/safecut", "--version"
    system "#{bin}/safecut", "--help"
  end
end
