# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Safecut < Formula
  desc "The cuts you'd defend at standup — find idle resources, simulate safely, and stop paying for what you don't use"
  homepage "https://github.com/Rafaelhdsg/safecut"
  version "2.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Rafaelhdsg/safecut/releases/download/v2.0.1/safecut_2.0.1_darwin_amd64.tar.gz"
      sha256 "2c1bc983bcaf30f3e12061477de6c864b4c5b336dde36c60fe5355ae3ef6deb2"

      define_method(:install) do
        bin.install "safecut"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Rafaelhdsg/safecut/releases/download/v2.0.1/safecut_2.0.1_darwin_arm64.tar.gz"
      sha256 "8db8021ea403584c311ff2a95da7dd098728a8b0a861228670ba81c53390810c"

      define_method(:install) do
        bin.install "safecut"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Rafaelhdsg/safecut/releases/download/v2.0.1/safecut_2.0.1_linux_amd64.tar.gz"
      sha256 "504955e1a72f191afe9e9fcd3783bd6a50d49f0eea8b907ed02497f9c7389f27"
      define_method(:install) do
        bin.install "safecut"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Rafaelhdsg/safecut/releases/download/v2.0.1/safecut_2.0.1_linux_arm64.tar.gz"
      sha256 "4a6314f1e271a5924ac69c2cc3cd920367e406511534d3860ab978561274d4ea"
      define_method(:install) do
        bin.install "safecut"
      end
    end
  end

  test do
    # Both forms must work: the explicit subcommand (stable API for
    # scripts/CI) and the cobra --version flag.
    assert_match "safecut", shell_output("#{bin}/safecut version")
    system "#{bin}/safecut", "--version"
    system "#{bin}/safecut", "--help"
  end
end
